### PR TITLE
Partial fix for dropped columns blowing up replication 

### PR DESCRIPTION
**Pull request by vartec**
Partial fix for dropped columns blowing up replication when replaying binlog with past events

Mitigates following error:
```
  File "/usr/local/lib/python2.7/dist-packages/pymysqlreplication/binlogstream.py", line 262, in fetchone
    self.__freeze_schema)
  File "/usr/local/lib/python2.7/dist-packages/pymysqlreplication/packet.py", line 98, in __init__
    freeze_schema = freeze_schema)
  File "/usr/local/lib/python2.7/dist-packages/pymysqlreplication/row_event.py", line 550, in __init__
    column_schema = self.column_schemas[i]
IndexError: list index out of range
```

This is just a superficial patch. It does not address deeper issue at hand, which is that `pymysqlreplication` has no good way of handling `RowEvent`s containing columns which have been dropped prior to `pymsqlreplication` start. The problem is always relying on current version of `information_schema` even though dealing with events that might be several versions in the past.

### CODE REVIEW

**Comment by vartec** [comment]
I've also created issue this and the underlying problem: https://github.com/noplay/python-mysql-replication/issues/118

**Comment by noplay** [comment]
Do you think it's possible to write a test for this ? I'm not sure

**Comment by vartec** [comment]
@noplay I've added unittest. Verified that it fails on your master.

**Comment by noplay** [comment]
Great thanks !

**Pull request merged**
