### PR TITLE
Add support for MariaDB GTID

### PR DESCRIPTION
**Pull request by Samira-El**
First of all, thanks for creating this library, it's great work!

This library works well with MariaDB when using binlog file and their position to stream changes, but only supports MySQL's GTID which is different in format than MariaDB's. This PR is for adding support for reading events from a given Mariadb GTID.  

Credit to https://github.com/OK-DMR/python-mariadb-replication for inspiring this PR.

### CODE REVIEW

**Comment by noplay** [comment]
Wow that's awesome ! I'm going to merge it and release a new version

**Comment by noplay** [comment]
Thanks I just released a 0.28 and credited you in the README.

**Comment by Samira-El** [comment]
Thank you for merging this, made my day!

**Comment by the4thdoctor** [comment]
W00T!

**Pull request merged**
