### PR TITLE
Implement Heartbeat

### PR DESCRIPTION
**Pull request by baloo**
I ended up debugging a slow startup with pymysqlreplication,
the stream "stucked" for a few seconds before seeing first events coming in.
For that purpose I ended up implementing HeartbeatLogEvent and
documenting observed mysql behavior.

I also implemented the heartbeat feature, which is required for the mysqld
to filter events in gtid mode.

### CODE REVIEW

**Comment by noplay** [comment]
Nice

**Comment by baloo** [comment]
@noplay I'm concerned about the new events in the stream. This may break the client apps. Maybe I should remove it from the default set.

**Comment by noplay** [comment]
In which scenario do you think it can break?

Le mar. 31 janv. 2017 à 22:55, Arthur Gautier <notifications@github.com> a
écrit :

**Comment by baloo** [comment]
New unexpected event in the stream. That's the only one I see.

**Comment by noplay** [comment]
If user don't want to receive unexpected events they should use the
only_events array. Perhaps we need to make that more clear.

Le mer. 1 févr. 2017 à 23:21, Arthur Gautier <notifications@github.com> a
écrit :

**Comment by baloo** [comment]
Agreed

**Pull request merged**
