### PR TITLE
Support for skipping the binlog until reaching specified timestamp.

### PR DESCRIPTION
**Pull request by vartec**
The rationale behind this is that as server fails over, the binlog position you've got stored from failed server might no longer be valid on the new one. With MySQL 5.6 you're fine, because you got GTIDs, but if you're using older MySQL there is no way of telling from which log position you should start. Timestamp  helps to _roughly_ know where to start. If your app is capable of dealing with duplicates, that is good enough.

### CODE REVIEW

**Comment by noplay** [comment]
Thanks! I'm away from home I will take a look on that when coming back at
the beginning of next week.

Le ven. 29 mai 2015 03:48, Bartek Ogryczak <notifications@github.com> a
écrit :

**Comment by bjoernhaeuser** [comment]
Why not implement that just in the application itself?

**Comment by noplay** [comment]
I think it's usefull if you changed the schema and want to skip the events.

**Comment by vartec** [comment]
@bjoernhaeuser the reason for doing here and not at application level is to avoid inflating rows into Python objects, which is CPU consuming and seriously limits the throughput. 

MySQL's binlog reader has similar option: https://dev.mysql.com/doc/refman/5.6/en/mysqlbinlog.html#option_mysqlbinlog_start-datetime

**Comment by vartec** [comment]
sorry about this back and forth with tests, but the outcome seems to depend heavily on MySQL version and configuration :-/

**Comment by vartec** [comment]
FYI, I've squashed the unittest commit mess.

**Comment by noplay** [comment]
Thanks

**Pull request merged**
