### PR TITLE
add support for BeginLoadQueryEvent and ExecuteLoadQueryEvent, update tests

### PR DESCRIPTION
**Pull request by jasonzzz**

### CODE REVIEW

**Comment by noplay** [comment]
Cool,

Do you think it's possible to write a test in order to avoid breaking it in another release?

**Comment by jasonzzz** [comment]
Hi, this case happens only when `binlog-format = statment`, but I find this [line](https://github.com/noplay/python-mysql-replication/blob/master/.travis.yml#L36) set `binlog-format = row`.

How can I change mysql config when testing this case using Travis CI?

**Comment by noplay** [comment]
You are right changing the config during the test is hard :(

**Comment by noplay** [comment]
I don't think we have an esay solution. Perhaps with Travis build matrix but it's start to be complicated. You can comment the test.

**Comment by jasonzzz** [comment]
I've commented the test. 

It builds [success](https://travis-ci.org/jasonzzz/python-mysql-replication/builds/63622067) under my repository though one [failed](https://travis-ci.org/noplay/python-mysql-replication/builds/63622085) here.

**Comment by noplay** [comment]
Thanks !

**Pull request merged**
