### PR TITLE
encode mysql time as python datetime.timedelta

### LINKED ISSUE #167: discrepancy between python datetime.time and mysql TIME
MYSQL [time](http://dev.mysql.com/doc/refman/5.7/en/time.html) supports a range of '-838:59:59.000000' to '838:59:59.000000' where was python [datetime.time](https://docs.python.org/2/library/datetime.html#time-objects) has a range of 0 <= hour < 24, 0 <= minute < 60, 0 <= second < 60, 0 <= microsecond < 1000000. It would be incorrect to encode mysql time into python datetime.time.

### PR DESCRIPTION
**Pull request by abrarsheikh**
this PR fixes #167

### CODE REVIEW

**Comment by noplay** [comment]
If someone can handle the PR validation it will be nice. I will be dad soon and I'm busy with painting stuff :P

**Comment by baloo** [comment]
@noplay I'll try to have a look this weekend, congrats on the new job of part-time painter :D

**Comment by abrarsheikh** [comment]
can someone also take a look at the build pipeline, seems to be broken for mysql5.7

**Comment by bjoernhaeuser** [comment]
@noplay congratulations :)

**Comment by bjoernhaeuser** [comment]
Build will be fixed after #170 is merged, then you need to rebase

**Pull request merged**
